export const indianStates = [
  { id: 1, label: "Andhra Pradesh", value: "andhra_pradesh" },
  { id: 2, label: "Arunachal Pradesh", value: "arunachal_pradesh" },
  { id: 3, label: "Assam", value: "assam" },
  { id: 4, label: "Bihar", value: "bihar" },
  { id: 5, label: "Chhattisgarh", value: "chhattisgarh" },
  { id: 6, label: "Goa", value: "goa" },
  { id: 7, label: "Gujarat", value: "gujarat" },
  { id: 8, label: "Haryana", value: "haryana" },
  { id: 9, label: "Himachal Pradesh", value: "himachal_pradesh" },
  { id: 10, label: "Jharkhand", value: "jharkhand" },
  { id: 11, label: "Karnataka", value: "karnataka" },
  { id: 12, label: "Kerala", value: "kerala" },
  { id: 13, label: "Madhya Pradesh", value: "madhya_pradesh" },
  { id: 14, label: "Maharashtra", value: "maharashtra" },
  { id: 15, label: "Manipur", value: "manipur" },
  { id: 16, label: "Meghalaya", value: "meghalaya" },
  { id: 17, label: "Mizoram", value: "mizoram" },
  { id: 18, label: "Nagaland", value: "nagaland" },
  { id: 19, label: "Odisha", value: "odisha" },
  { id: 20, label: "Punjab", value: "punjab" },
  { id: 21, label: "Rajasthan", value: "rajasthan" },
  { id: 22, label: "Sikkim", value: "sikkim" },
  { id: 23, label: "Tamil Nadu", value: "tamil_nadu" },
  { id: 24, label: "Telangana", value: "telangana" },
  { id: 25, label: "Tripura", value: "tripura" },
  { id: 26, label: "Uttar Pradesh", value: "uttar_pradesh" },
  { id: 27, label: "Uttarakhand", value: "uttarakhand" },
  { id: 28, label: "West Bengal", value: "west_bengal" },
  { id: 29, label: "Andaman and Nicobar Islands", value: "andaman_nicobar_islands" },
  { id: 30, label: "Chandigarh", value: "chandigarh" },
  { id: 31, label: "Dadra and Nagar Haveli and Daman and Diu", value: "dadra_nagar_haveli_daman_diu" },
  { id: 32, label: "Delhi", value: "delhi" },
  { id: 33, label: "Jammu and Kashmir", value: "jammu_kashmir" },
  { id: 34, label: "Ladakh", value: "ladakh" },
  { id: 35, label: "Lakshadweep", value: "lakshadweep" },
  { id: 36, label: "Puducherry", value: "puducherry" }
];